name: WebApp Deployment
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      # Add Scala.js build step
      - name: Build Scala.js
        run: sbt fullOptJS

      - run: npm install && npm run build

      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Add this to deploy to a separate URL
          publish_branch: gh-pages-app